CREATE DATABASE rkis;

\connect rkis

CREATE TABLE IF NOT EXISTS Dishes (
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    name     VARCHAR,
    color    VARCHAR,
    material VARCHAR,
    width   NUMERIC,
    depth    NUMERIC,
    price    NUMERIC,
    quantity INTEGER
);